---
galaxy_info:
  author: Till Klocke
  description: Install alfred daemon
  company: Freifunk Dortmund
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - monitoring
  - networking
dependencies: []
