---
- name: Ensure some useful packages are installed
  apt: name={{ item }} install_recommends=no
  with_items:
    - bash-completion
    - vim
    - htop
    - mtr-tiny
    - bind9-host
    - curl
    - tmux
    - psmisc
    - ngrep
    - aptitude
    - iperf
    - pv

- name: Ensure vim is default editor
  alternatives: name=editor path=/usr/bin/vim.basic
- name: Set defaults for vim
  copy: src=vimrc dest=/etc/vim/vimrc.local
