---

- name: Ensure deb-src ist disabled in sources.list
  replace: dest=/etc/apt/sources.list regexp='^(deb-src .*)$' replace='#\1'

- name: Ensure lsb-release is installed
  apt: name=lsb-release
- name: Ensure Debian backports repository is installed
  apt_repository: repo='deb http://ftp.de.debian.org/debian {{ ansible_lsb.codename|lower }}-backports main'

# - name: Ensure FFDO repository key is installed
#   apt_key:
#     id: B257AE19
#     data: "{{ lookup('file', 'markus.gpg') }}"

# - name: ensure FFDO APT repository is installed
#   apt_repository: repo='deb {{ ffdo_repo }} {{ ansible_lsb.codename|lower }} main'

- name: Update APT cache
  apt: update_cache=yes cache_valid_time=3600

# - name: ensure all packages are up to date
#   apt: upgrade=dist install_recommends=no dpkg_options='force-confold,force-confdef'
